
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jun
 */
public class LinkFrame extends javax.swing.JFrame {
    String day = getCurrentDay();
    String edu = null;
    /**
     * Creates new form LinkFrame
     */
    public LinkFrame() {
        initComponents();
        setLayout(null); // 레이아웃 매니저 제거 (절대 위치 사용)
        
        
        
        try {
        // 월요일 수요일은 성폭력 예방 교육 
            if (day.equals("월요일") || day.equals("수요일")) {
                edu = "성폭력 예방 교육";
            }
            // 화요일은 장애인 인식 개선 교육 
            else if( day.equals("화요일")) {
                edu = "장애인 인식 개선 교육";
            } 
            // 목요일은 직장 내 따돌림 예방 교육
            else if (day.equals("목요일")) {
                edu = "직장 내 따돌림 예방 교육";
            }
            // 금요일은 산업 재해 예방 교육 
            else {
                edu = "산업 재해 예방 교육";
            }
        
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        daylbl.setText(getCurrentDay() + "은 ");
        checklbl.setText(edu + "입니다.");
    }
    
    // 요일을 계산하는 메서드
    private String getCurrentDay() {
        String[] days = {"일요일", "월요일", "화요일", "수요일", "목요일", "금요일", "토요일"};
        java.util.Calendar calendar = java.util.Calendar.getInstance();
        int dayIndex = calendar.get(java.util.Calendar.DAY_OF_WEEK) - 1;
        return days[dayIndex];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        edulbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        linklbl = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        daylbl = new javax.swing.JLabel();
        checklbl = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        edulbl.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        edulbl.setText("교육자료");

        linklbl.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        linklbl.setForeground(new java.awt.Color(0, 51, 255));
        linklbl.setText("[교육 자료 링크]  클릭 시 문제 표시");
        linklbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linklblMouseClicked(evt);
            }
        });

        daylbl.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        daylbl.setText("요일은 ");

        checklbl.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        checklbl.setText("교육입니다.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(linklbl)
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(edulbl)
                        .addGap(229, 229, 229))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(daylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checklbl, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(edulbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(linklbl)
                .addGap(31, 31, 31)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daylbl)
                    .addComponent(checklbl))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void linklblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linklblMouseClicked
        // TODO add your handling code here:

        try {
        // 월요일 수요일은 성폭력 예방 교육 
            if (day.equals("월요일") || day.equals("수요일")) {
                edu = "성폭력 예방 교육";
                Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=dLehSeLbiJc&lis육t=PLjN7ShteQfYT7bUCQ9LLjKW5j7Zl7p-YU&index=1"));
            }
            // 화요일은 장애인 인식 개선 교육 
            else if( day.equals("화요일")) {
                edu = "장애인 인식 개선 교육";
                Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=VRBDaQwvvHg&list=PLjN7ShteQfYT7bUCQ9LLjKW5j7Zl7p-YU&index=3"));
            } 
            // 목요일은 직장 내 따돌림 예방 교육
            else if (day.equals("목요일")) {
                edu = "직장 내 따돌림 예방 교육";
                Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=zFA1puJa24o&list=PLjN7ShteQfYT7bUCQ9LLjKW5j7Zl7p-YU&index=6"));
            }
            // 금요일은 산업 재해 예방 교육 
            else {
                edu = "산업 재해 예방 교육";
                Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=glXV9-zDaKU&list=PLPhfWH-cPSSwQT17BayJnm7bo5P-iyVtJ&index=2"));
            }
        
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        QuizFrame quizFrame = null;
        try {
            quizFrame = new QuizFrame(); // 객체 생성
        } catch (IOException ex) {
            Logger.getLogger(LinkFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        quizFrame.setVisible(true); // Quiz 프레임 표시 
        this.dispose();             // 현재 프레임 닫기
        
    }//GEN-LAST:event_linklblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LinkFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LinkFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LinkFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LinkFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LinkFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel checklbl;
    private javax.swing.JLabel daylbl;
    private javax.swing.JLabel edulbl;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel linklbl;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
