
import domain.Question;
import java.io.IOException;
import javax.swing.ButtonGroup;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jun
 */
public class QuizFrame extends javax.swing.JFrame {
    private DB_MAN db = new DB_MAN(); // DB 연결 객체
    private String dayCategory; // 현재 요일에 따른 카테고리
    private int dayId; // 현재 카테고리 ID
    private int currentQuestionIndex = 0; // 현재 문제 인덱스
    List<Question> questions = new ArrayList<>();// 질문을 담을 리스트
    

    


    /**
     * Creates new form QuizFrame
     */
    public QuizFrame() throws IOException {
        initComponents();
        setCategoryByDay(); // 요일 보고 카테고리 적어두기. 
        loadQuestion(); // 질문 데이터 불러오기
        displayQuestion(); // 첫 번째 문제 표시
    }
    
    
    
    private void setCategoryByDay() {
        String[] days = {"일요일", "월요일", "화요일", "수요일", "목요일", "금요일", "토요일"};
        String[] categories = {"기타", "성폭력 예방 교육", "장애인 인식 개선 교육", 
                               "성폭력 예방 교육", "직장 내 따돌림 예방 교육", 
                               "산업 재해 예방 교육", "기타"};

        java.util.Calendar calendar = java.util.Calendar.getInstance();
        int dayIndex = calendar.get(java.util.Calendar.DAY_OF_WEEK) - 1;
        dayCategory = categories[dayIndex];

        if (days[dayIndex].equals("월요일") || days[dayIndex].equals("수요일")) { 
            dayId = 1;
        } else if (days[dayIndex].equals("화요일")) { 
            dayId = 2;
        } else if (days[dayIndex].equals("목요일")) { 
            dayId = 3;
        } else { 
            dayId = 4;
        }
        // jLabel1에 카테고리 표시
        catelbl.setText("카테고리 : " + dayCategory);
    }
    
    private void displayQuestion() {
        // 현재 문제 인덱스가 유효한지 확인
        if (currentQuestionIndex < questions.size()) {
            Question currentQuestion = questions.get(currentQuestionIndex);
            qlbl.setText("문제 : " + currentQuestion.getQuest());
            q1.setText(currentQuestion.getQ1());
            q2.setText(currentQuestion.getQ2());
            q3.setText(currentQuestion.getQ3());
            q4.setText(currentQuestion.getQ4());
        } else {
            // 더 이상 문제가 없으면 종료 메시지 표시
            qlbl.setText("문제를 모두 풀었습니다!");
            q1.setVisible(false);
            q2.setVisible(false);
            q3.setVisible(false);
            q4.setVisible(false);
            submitbutton.setEnabled(false); // 제출 버튼 비활성화
        }
    }

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {
        // 다음 문제로 이동
        currentQuestionIndex++;
        displayQuestion();
    }
    
    private void loadQuestion() throws IOException {
    try {
        db.dbOpen(); // 데이터베이스 연결
        String query = "SELECT q.id AS question_id, q.quest, q.q1, q.q2, q.q3, q.q4, q.correct_answer "
                         + "FROM Question q "
                         + "WHERE q.category_id = ? "
                         + "ORDER BY RAND() LIMIT 5"; // 랜덤으로 5개 선택
        PreparedStatement pstmt = db.DB_con.prepareStatement(query);
        pstmt.setInt(1, dayId); // 카테고리를 기준으로 데이터 필터링
        ResultSet rs = pstmt.executeQuery();

        

        // ResultSet에서 데이터를 리스트에 저장
        while (rs.next()) {
            Question question = new Question(
                rs.getInt("question_id"),
                rs.getString("quest"),
                rs.getString("q1"),
                rs.getString("q2"),
                rs.getString("q3"),
                rs.getString("q4"),
                rs.getInt("correct_answer")
            );
            questions.add(question);
        }


        rs.close();
        pstmt.close();
        db.dbClose(); // 데이터베이스 연결 닫기
    } catch (SQLException e) {
        e.printStackTrace();
        System.out.println("질문 로드 중 오류 발생: " + e.getMessage());
    }
    
}
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        catelbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        qlbl = new javax.swing.JLabel();
        q1 = new javax.swing.JRadioButton();
        q2 = new javax.swing.JRadioButton();
        q3 = new javax.swing.JRadioButton();
        q4 = new javax.swing.JRadioButton();
        submitbutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        catelbl.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        catelbl.setForeground(new java.awt.Color(0, 0, 255));
        catelbl.setText("카테고리 :");

        qlbl.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        qlbl.setText("문제 :");

        q1.setText("jRadioButton1");
        q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1ActionPerformed(evt);
            }
        });

        q2.setText("jRadioButton2");

        q3.setText("jRadioButton3");

        q4.setText("jRadioButton4");

        submitbutton.setText("제출");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("* 패널티 규칙에 따라 정답/오답 표시");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q3)
                    .addComponent(q2)
                    .addComponent(q1)
                    .addComponent(qlbl)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                    .addComponent(catelbl)
                    .addComponent(q4)
                    .addComponent(jSeparator2))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(catelbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(qlbl)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(q1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q4)
                .addGap(26, 26, 26)
                .addComponent(submitbutton)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new QuizFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(QuizFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel catelbl;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton q1;
    private javax.swing.JRadioButton q2;
    private javax.swing.JRadioButton q3;
    private javax.swing.JRadioButton q4;
    private javax.swing.JLabel qlbl;
    private javax.swing.JButton submitbutton;
    // End of variables declaration//GEN-END:variables
}
